//! Turn the measured POSIX-bracket table into Rust.
//!
//! Six of Onigmo's fourteen brackets are unions of Unicode general categories
//! that `char`'s own predicates do not expose: `Nd` alone, `Alphabetic + Nd`,
//! `P*`, "assigned minus `C*`". `#180` had three ways to close them — embed the
//! measured ranges, take a Unicode-tables dependency, or generate Rust from the
//! oracle — and this is the third.
//!
//! A dependency was the one rejected on purpose. Its Unicode version has to be
//! kept in step with the one CRuby was built against, and a mismatch shows up as
//! exactly the kind of quiet per-codepoint disagreement `#178`'s audit was
//! written to catch. Generating from `tests/posix.txt` keeps a *measurement* as
//! the source of truth: that file is regenerated from a live CRuby by
//! `scripts/regexp-oracle.rb --generate` and re-checked against one by CI.
//!
//! Ranges rather than a bitset: 2,353 of them across the six, sorted, so a
//! lookup is a binary search over ~19 KB of `.rodata` and costs nothing at boot
//! — which matters, because the spec harness boots one heap per example.

use std::fmt::Write as _;
use std::path::PathBuf;

/// The brackets that need a table. The other eight are exact on `char`'s own
/// predicates and stay there — cheaper than a binary search, and already
/// measured as agreeing on every codepoint.
const GENERATED: &[&str] = &["digit", "alnum", "print", "graph", "word", "punct"];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let table = manifest.join("tests/posix.txt");
    println!("cargo:rerun-if-changed={}", table.display());
    println!("cargo:rerun-if-changed=build.rs");

    let source = std::fs::read_to_string(&table)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", table.display()));

    let mut out = String::from(
        "// Generated by build.rs from tests/posix.txt. Do not edit.\n\
         //\n\
         // One sorted, non-overlapping range list per bracket, as inclusive\n\
         // `(low, high)` pairs of scalar values.\n",
    );
    let mut written = 0;
    for line in source.lines() {
        let line = line.trim_end();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let Some((name, fields)) = line.split_once('\t') else {
            continue;
        };
        if !GENERATED.contains(&name) {
            continue;
        }
        let mut ranges: Vec<(u32, u32)> = Vec::new();
        for field in fields.split(';').filter(|f| !f.is_empty()) {
            let (low, high) = match field.split_once('-') {
                Some((low, high)) => (low, high),
                // A bare `LO` is a one-codepoint range.
                None => (field, field),
            };
            let parse = |s: &str| {
                u32::from_str_radix(s, 16)
                    .unwrap_or_else(|e| panic!("{name}: bad codepoint {s:?}: {e}"))
            };
            ranges.push((parse(low), parse(high)));
        }
        // The lookup is a binary search, so sortedness is a correctness
        // requirement rather than a tidiness one. The generator emits sorted
        // ranges today; assert it here so a change to the generator fails the
        // build instead of silently making the search miss.
        assert!(
            ranges.windows(2).all(|w| w[0].1 < w[1].0),
            "{name}: ranges in posix.txt are not sorted and disjoint"
        );
        let _ = writeln!(
            out,
            "static {}: &[(u32, u32)] = &[",
            name.to_uppercase().as_str()
        );
        for (low, high) in &ranges {
            let _ = writeln!(out, "    (0x{low:X}, 0x{high:X}),");
        }
        out.push_str("];\n");
        written += 1;
    }
    assert_eq!(
        written,
        GENERATED.len(),
        "tests/posix.txt is missing a bracket the engine generates a table for"
    );

    let dest =
        PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("posix_tables.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}
