#!/usr/bin/env bash
#
# Run the benchmarks in `bench/`.
#
#   scripts/bench.sh                 every benchmark
#   scripts/bench.sh regex_captures  one of them
#   scripts/bench.sh --ruby          the same regex patterns on system ruby
#
# Numbers go in the PR, not into the repo — `docs/roadmap.md`, rule 7. The one
# exception is `bench/spec-status.md`, which is generated by
# `scripts/spec-status.sh` and committed on purpose: it is the progress bar.
#
# `--ruby` times `bench/regex-patterns.txt` on the system Ruby with YJIT, which
# is the comparison `CLAUDE.md` asks engine benchmarks to make. Both sides read
# that one file, so neither can quietly measure a different pattern.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
patterns="$repo_root/bench/regex-patterns.txt"

if [[ "${1:-}" == "--ruby" ]]; then
  command -v ruby >/dev/null || { echo "bench.sh: no ruby on PATH" >&2; exit 2; }
  ruby --yjit -e '
    iterations = 20_000
    puts "system #{RUBY_DESCRIPTION}"
    puts "  %-20s  %12s  %7s" % ["pattern", "per match", "groups"]
    File.readlines(ARGV[0]).each do |line|
      next if line.start_with?("#") || line.strip.empty?
      name, source, subject = line.chomp("\n").split("\t", 3)
      re = Regexp.new(source)
      # Min of five, matching `time()` in the Rust benchmarks: the quantity is
      # the time with nothing else interfering.
      best = (1..5).map do
        started = Process.clock_gettime(Process::CLOCK_MONOTONIC)
        iterations.times { re.match(subject) }
        (Process.clock_gettime(Process::CLOCK_MONOTONIC) - started) / iterations
      end.min
      per = best < 1e-6 ? "%.0fns" % (best * 1e9) : "%.3fµs" % (best * 1e6)
      puts "  %-20s  %12s  %7d" % [name, per, re.names.size + source.scan(/(?<!\\)\((?!\?)/).size]
    end
  ' "$patterns"
  exit 0
fi

# `cargo bench` with `harness = false` just runs each `main`, so a name selects
# one the way `--bench` does.
if [[ $# -gt 0 ]]; then
  exec cargo bench --bench "$1"
fi
exec cargo bench --benches
