#!/usr/bin/env ruby
# frozen_string_literal: true

# The oracle behind `crates/spinel-vm/src/encoding_table.rs` (#19): CRuby's
# encodings, and the Unicode character classes `String#succ` steps within.
#
# Spinel's `Encoding` objects are CRuby's list: every name, in CRuby's index
# order, with its aliases and its two flags. The table is generated from a real
# Ruby rather than written by hand, so `Encoding::EUC_JP.ascii_compatible?` is
# a measurement.
#
#   ruby scripts/encoding-table.rb --check      # CI: agree, or fail
#   ruby scripts/encoding-table.rb --generate   # rewrite the table
#
# `locale`, `external`, `filesystem` and `internal` are left out: CRuby
# resolves them from the process's environment at boot, so they are not
# properties of an encoding and `core/encoding.rb` answers them itself.

TABLE = File.expand_path("../crates/spinel-vm/src/encoding_table.rs", __dir__)
RUNTIME_ALIASES = %w[locale external filesystem internal].freeze

# Codepoint ranges Onigmo's `[[:alpha:]]` or `[[:digit:]]` matches in UTF-8:
# the character classes `String#succ` steps within (#19), as CRuby's Unicode
# version has them.
def ranges(pattern)
  out = []
  start = nil
  last = nil
  (0..0x10FFFF).each do |code|
    next if code >= 0xD800 && code <= 0xDFFF
    if code.chr(Encoding::UTF_8).match?(pattern)
      start ||= code
      last = code
    elsif start
      out << [start, last]
      start = nil
    end
  end
  out << [start, last] if start
  out.map { |(first, final)| format("    (0x%X, 0x%X),", first, final) }
end

def render
  alpha = ranges(/\A[[:alpha:]]\z/)
  digit = ranges(/\A[[:digit:]]\z/)
  aliases = Hash.new { |h, k| h[k] = [] }
  Encoding.aliases.each do |name, target|
    aliases[target] << name unless RUNTIME_ALIASES.include?(name)
  end
  constants = Encoding.constants.sort.filter_map do |name|
    value = Encoding.const_get(name)
    format("    (%s, %d),", name.to_s.inspect, Encoding.list.index(value)) if value.is_a?(Encoding)
  end
  rows = Encoding.list.map do |encoding|
    names = [encoding.name] + aliases[encoding.name].sort
    format("    (%s, %s, %s),", names.map(&:inspect).join(", ").then { |n| "&[#{n}]" },
           encoding.ascii_compatible?, encoding.dummy?)
  end
  <<~RUST
    //! CRuby's encodings, in its index order (#19). Generated by
    //! `scripts/encoding-table.rb --generate` from ruby #{RUBY_VERSION}; do not edit.
    //!
    //! Each row is the names (canonical first, then aliases), whether the
    //! encoding is ASCII-compatible, and whether it is a dummy.

    #[rustfmt::skip]
    pub const ENCODINGS: &[(&[&str], bool, bool)] = &[
    #{rows.join("\n")}
    ];

    /// Every constant CRuby defines on `Encoding` for an encoding, and the
    /// index it names. CRuby derives them from the names by rules of its own
    /// (`EUC_JP`, `EUCJP` and `EucJP` are one encoding); this is the result.
    #[rustfmt::skip]
    pub const CONSTANTS: &[(&str, u8)] = &[
    #{constants.join("\n")}
    ];

    /// Unicode #{RbConfig::CONFIG["UNICODE_VERSION"]} codepoint ranges that are alphabetic, as
    /// Onigmo's `[[:alpha:]]` decides — what `String#succ` treats as a letter.
    #[rustfmt::skip]
    pub const ALPHA: &[(u32, u32)] = &[
    #{alpha.join("\n")}
    ];

    /// The decimal digits (`[[:digit:]]`): what `String#succ` treats as a digit.
    #[rustfmt::skip]
    pub const DIGIT: &[(u32, u32)] = &[
    #{digit.join("\n")}
    ];
  RUST
end

case ARGV.first
when "--generate"
  File.write(TABLE, render)
  puts "wrote #{TABLE}"
when "--check"
  if File.read(TABLE).sub(/from ruby [\d.]+/, "") == render.sub(/from ruby [\d.]+/, "")
    puts "#{TABLE} matches ruby #{RUBY_VERSION}"
  else
    warn "#{TABLE} disagrees with ruby #{RUBY_VERSION}: run --generate and review the diff"
    exit 1
  end
else
  warn "usage: #{$PROGRAM_NAME} --check | --generate"
  exit 2
end
