#!/usr/bin/env ruby
# frozen_string_literal: true

# The oracle behind `crates/spinel-vm/tests/exceptions.txt`.
#
# `rescue TypeError` picks a handler by walking a class's superclass chain, so
# the chain has to be Ruby's. Which classes exist, and which one each inherits
# from, is not something to read out of `error.c` and retype: it is measured
# here, from a real Ruby's own `ObjectSpace`, and CI re-checks it.
#
#   ruby scripts/exceptions-oracle.rb --check      # CI: agree, or fail
#   ruby scripts/exceptions-oracle.rb --generate   # rewrite the table
#
# The table is one `Name < Superclass` per line, **parents before children**, so
# `Classes::bootstrap` can define them in file order and never look ahead. A
# trailing `# own initialize` marks a class whose `initialize` is its own rather
# than `Exception`'s: Spinel implements only `Exception#initialize`, so `new` on
# one of those would answer as if it had validated arguments it never looked at,
# and refuses instead until `core/*.rb` defines them.
#
# Only core classes are listed: a name with no `::` in it that is still a
# constant on `Object` when Ruby starts with no gems and nothing required. That
# is exactly the set a Ruby program can name before it has loaded anything,
# which is the set Spinel bootstraps. `fatal` is excluded because it is not
# reachable as a constant — `rescue fatal` is a NameError in Ruby too.

TABLE = File.expand_path("../crates/spinel-vm/src/exceptions.txt", __dir__)

HEADER = <<~TEXT
  # CRuby's exception hierarchy, measured. Do not edit by hand.
  #
  # Generated by `scripts/exceptions-oracle.rb --generate`; CI re-runs it with
  # `--check`. One `Name < Superclass` per line, parents before children, which
  # is the order `Classes::bootstrap` defines them in.
  #
  # `Exception < Object` is the root and is bootstrapped as a `Builtin` before
  # this table is read; it is listed anyway so the file is the whole truth
  # rather than the truth minus one line.
TEXT

# Every core exception class, as `[name, superclass_name]`.
def measure
  classes = ObjectSpace.each_object(Class).select { |c| (c <= Exception) rescue false }
  core = classes.select do |c|
    name = (c.name rescue nil)
    # `fatal` is lowercase and `const_defined?` raises on it, so the shape of
    # the name is checked before the name is used as one.
    name && name.match?(/\A[A-Z]\w*\z/) &&
      Object.const_defined?(name) && Object.const_get(name).equal?(c)
  end

  # Parents before children: repeatedly emit whatever's superclass is already
  # placed. A plain sort by name would put `KeyError` before `IndexError`, and
  # then the bootstrap would have to look ahead.
  ordered = []
  placed = { Object => true }
  remaining = core.sort_by { |c| c.name }
  until remaining.empty?
    ready, remaining = remaining.partition { |c| placed[c.superclass] }
    abort "cycle or missing superclass near #{remaining.first}" if ready.empty?
    ready.each { |c| ordered << c; placed[c] = true }
  end
  ordered.map { |c| [c.name, c.superclass.name, c.instance_method(:initialize).owner != Exception] }
end

def render
  rows = measure
  width = rows.map { |name, _| name.length }.max
  pair = rows.map { |name, sup, _| format("%-#{width}s < %s", name, sup) }
  pad = pair.map(&:length).max
  body = rows.each_with_index.map { |(_, _, own), i|
    own ? format("%-#{pad}s  # own initialize", pair[i]) : pair[i]
  }.join("\n")
  "#{HEADER}\n#{body}\n"
end

case ARGV[0]
when "--generate"
  File.write(TABLE, render)
  puts "wrote #{measure.length} classes to #{TABLE.sub("#{Dir.pwd}/", "")}"
when "--check"
  unless File.exist?(TABLE)
    abort "exceptions-oracle: #{TABLE} is missing; run --generate"
  end
  actual = render
  recorded = File.read(TABLE)
  if actual == recorded
    puts "#{measure.length} exception classes on #{RUBY_ENGINE} #{RUBY_VERSION}: table agrees"
  else
    warn "exceptions-oracle: the table disagrees with #{RUBY_ENGINE} #{RUBY_VERSION}"
    warn "  regenerate it: ruby scripts/exceptions-oracle.rb --generate"
    recorded_lines = recorded.lines
    actual.lines.each_with_index do |line, index|
      warn "  -#{recorded_lines[index]&.chomp}\n  +#{line.chomp}" if recorded_lines[index] != line
    end
    exit 1
  end
else
  abort "usage: exceptions-oracle.rb --check | --generate"
end
