#!/usr/bin/env ruby
# frozen_string_literal: true

# The oracle behind `crates/spinel-regex/tests/oracle.txt`.
#
# Ruby's regex dialect is Onigmo's, and the interesting parts of it are exactly
# the parts that cannot be read off a reference page and retyped: whether `\w`
# is ASCII, whether `[[:alpha:]]` is not, where a capture lands after an empty
# iteration, what a backreference to an unmatched group does. Every one of those
# is measured here, from a real Ruby, and CI re-checks it.
#
#   ruby scripts/regexp-oracle.rb --check       # CI: agree, or fail
#   ruby scripts/regexp-oracle.rb --generate    # rewrite the table
#   ruby scripts/regexp-oracle.rb --survey      # the engine-choice measurement
#
# The pattern corpus is every regexp literal that appears in ruby/spec's
# `language/regexp/`, which is the set the slice is judged on, plus a handful of
# hand-added patterns for behaviour the corpus exercises only indirectly. Each
# pattern is run against a fixed probe corpus of subjects chosen to separate the
# dialects: newlines for the anchors, non-ASCII for the character classes,
# repeated characters for the quantifiers.
#
# `--survey` is the measurement that settled the engine question in
# `docs/engine.md`. It reports how far a candidate backend would get without
# reimplementing the dialect, and is kept so the decision can be re-run rather
# than believed.

require "prism"

ROOT = File.expand_path("..", __dir__)
CORPUS = File.join(ROOT, "spec", "ruby", "language", "regexp")
TABLE = File.join(ROOT, "crates", "spinel-regex", "tests", "oracle.txt")
POSIX_TABLE = File.join(ROOT, "crates", "spinel-regex", "tests", "posix.txt")

# Subjects chosen so that two engines which disagree about the dialect give
# different answers on at least one of them.
INPUTS = [
  "", "foo", "foo\n", "\nfoo", "foo\nbar", "FOO", "a", "ab", "abc", "aaa",
  "foo bar", " foo ", "x\ny", "1", "12", "a1b2", "\t", "é", "あ", "٣",
  "()", "[c]", "aXb", " ", "a b", "foobar", "barfoo", "\r\n", "-", "_"
].freeze

# Behaviour `language/regexp/` leans on but never spells out in one literal.
EXTRA = [
  '(a*)*', '(a*)+', '(?:(a)|b)\1', '(?=(a))', '(?>a+)ab', 'a++ab',
  '[a-z&&[^b]]', '[[:alpha:]]', '[[:digit:]]', '\h', '\H',
  'a{2}?', 'a{2}+', 'a{2,3}?', 'a{2,}?', '(?i:a)b', 'a(?i)b',
  '(?<n>a)\k<n>', 'foo\Z', 'foo\z', '\Afoo', '^bar', 'foo$'
].freeze

# Patterns whose *meaning* is fine but whose timing is not: Ruby answers a
# pathological backtracker slowly, and this engine refuses. Nothing to compare.
SKIP = ['(a+)+b'].freeze

def literals
  found = []
  Dir[File.join(CORPUS, "**", "*.rb")].sort.each do |file|
    result = Prism.parse_file(file)
    next unless result.success?

    result.value.breadth_first_search do |node|
      found << node.unescaped if node.is_a?(Prism::RegularExpressionNode)
      false
    end
  end
  (found + EXTRA).uniq.reject { |source| SKIP.include?(source) }.sort
end

# One line per pattern: the pattern, then one field per probe subject.
#
# A field is `-` for no match, or `begin,end` in **characters** followed by each
# group's begin,end or `~` when the group took no part. Characters rather than
# bytes because that is what `MatchData#begin` answers, and the point of the
# table is to be the thing Spinel has to reproduce.
def measure(source)
  regexp =
    begin
      Regexp.new(source)
    rescue RegexpError => e
      return "!#{e.message.lines.first.strip}"
    end

  INPUTS.map { |subject| probe(regexp, subject) }.join(" ")
end

def probe(regexp, subject)
  match = regexp.match(subject)
  return "-" if match.nil?

  groups = (1...match.size).map do |i|
    match.begin(i) ? "#{match.begin(i)},#{match.end(i)}" : "~"
  end
  ["#{match.begin(0)},#{match.end(0)}", *groups].join(":")
rescue StandardError => e
  "!#{e.class}"
end

HEADER = <<~TEXT
  # Ruby's regex dialect, measured. Do not edit by hand.
  #
  # Generated by `scripts/regexp-oracle.rb --generate`; CI re-runs it with
  # `--check`, and `crates/spinel-regex/tests/oracle.rs` replays every line
  # through the engine.
  #
  # One pattern per line: the pattern as a Ruby string literal, a tab, then one
  # field per probe subject. A field is `-` for no match, `!message` when the
  # pattern itself is rejected, or `begin,end` in characters for the whole
  # match followed by `:begin,end` per group, with `~` for a group that took
  # no part.
  #
  # The subjects, in order:
TEXT

def render
  lines = literals.map { |source| "#{source.inspect}\t#{measure(source)}" }
  subjects = INPUTS.each_slice(6).map { |slice| "#   #{slice.map(&:inspect).join(' ')}" }
  [HEADER.chomp, *subjects, "", *lines, ""].join("\n")
end

# The measurement that settled the engine question. Reports how a candidate
# backend that is not Onigmo would fare, so the decision in `docs/engine.md`
# can be re-run rather than taken on trust.
def survey
  sources = literals
  valid = sources.reject { |s| measure(s).start_with?("!") }
  puts "patterns in language/regexp/ (plus #{EXTRA.length} hand-added): #{sources.length}"
  puts "  CRuby accepts: #{valid.length}"
  puts "  CRuby rejects: #{sources.length - valid.length}"
  puts
  puts "Dialect features present, which any non-Onigmo backend must supply:"
  {
    "backreference \\1" => /\\\d/,
    "named group (?<n>)" => /\(\?</,
    "lookbehind (?<=|(?<!" => /\(\?<[=!]/,
    "atomic (?>) or possessive" => /\(\?>|[*+?}]\+/,
    "POSIX bracket [[:x:]]" => /\[\[:/,
    "class intersection &&" => /&&/,
    "\\h hex shorthand" => /\\[hH]/,
    "absent operator (?~)" => /\(\?~/,
    "subexpression call \\g<>" => /\\g</,
    "conditional (?(n))" => /\(\?\(/,
    "keep \\K" => /\\K/,
    "\\R or \\X" => /\\[RX]/
  }.each do |name, probe|
    hits = sources.count { |s| s.match?(probe) }
    puts format("  %-28s %3d patterns", name, hits) if hits.positive?
  end
end

# The fourteen POSIX brackets, measured over every codepoint rather than read
# off a reference page.
#
# These are the part of the dialect that is easiest to get *nearly* right: the
# shorthands (`\w`, `\s`) are ASCII in Ruby and the brackets are not, so an
# engine built on Rust's `char` predicates lands close enough that sampling a
# few characters agrees. `[[:blank:]]` is the case that proves sampling is not
# enough — it is Zs plus tab, and `char::is_whitespace` is Zs plus the line
# separators, so the two differ on exactly the characters nobody probes by
# hand. So this table is exhaustive: every scalar value, as ranges.
POSIX = %w[
  alpha digit alnum upper lower space blank print graph cntrl xdigit word
  ascii punct
].freeze

SURROGATES = (0xD800..0xDFFF).freeze

# Every codepoint the bracket matches, as ascending `lo-hi` ranges in hex.
# Surrogates are skipped: they are not scalar values, Ruby cannot build a
# String from one, and Rust's `char` cannot hold one either.
def posix_ranges(name)
  regexp = Regexp.new("[[:#{name}:]]")
  ranges = []
  run_start = nil
  (0..0x10FFFF).each do |cp|
    held =
      if SURROGATES.cover?(cp)
        false
      else
        regexp.match?(cp.chr(Encoding::UTF_8))
      end
    if held
      run_start ||= cp
    elsif run_start
      ranges << [run_start, cp - 1]
      run_start = nil
    end
  end
  ranges << [run_start, 0x10FFFF] if run_start
  ranges
end

def posix_render
  lines = POSIX.map do |name|
    fields = posix_ranges(name).map do |lo, hi|
      lo == hi ? format("%X", lo) : format("%X-%X", lo, hi)
    end
    "#{name}\t#{fields.join(';')}"
  end
  [POSIX_HEADER.chomp, "", *lines, ""].join("\n")
end

POSIX_HEADER = <<~TEXT
  # Ruby's POSIX brackets, measured over every codepoint. Do not edit by hand.
  #
  # Generated by `scripts/regexp-oracle.rb --generate`; CI re-runs it with
  # `--check`, and a unit test in `crates/spinel-regex/src/exec.rs` replays
  # every range through the engine's own class predicate.
  #
  # One bracket per line: the name, a tab, then the codepoints it matches as
  # `;`-separated hex ranges, `LO-HI` or a bare `LO` for a single codepoint.
  # Surrogates are excluded — Ruby cannot build a String from one and Rust's
  # `char` cannot hold one, so neither engine has an answer to compare.
TEXT

case ARGV[0]
when "--generate"
  File.write(TABLE, render)
  puts "wrote #{TABLE}"
  File.write(POSIX_TABLE, posix_render)
  puts "wrote #{POSIX_TABLE}"
when "--check"
  stale = []
  {TABLE => method(:render), POSIX_TABLE => method(:posix_render)}.each do |path, build|
    current = File.exist?(path) ? File.read(path) : ""
    stale << path unless current == build.call
  end
  if stale.empty?
    puts "regexp oracle is current"
  else
    warn "regexp oracle is stale: regenerate with scripts/regexp-oracle.rb --generate"
    warn "  ruby #{RUBY_VERSION} disagrees with the checked-in table"
    stale.each { |path| warn "  #{path}" }
    exit 1
  end
when "--survey"
  survey
else
  abort "usage: regexp-oracle.rb --check | --generate | --survey"
end
