#!/usr/bin/env bash
#
# Merge the record listings of several mspec processes into one report (#145).
#
#   scripts/spec-report.sh [--table] [--blocked=N] LISTING...
#
# Each LISTING is one process's stdout under `SPINEL_SPEC_LIST=1`: a `LIST`
# line per record, `LIST<TAB>kind<TAB>file<TAB>description<TAB>detail`, the
# kinds as `spec/spinel/report.rb` lists them. `scripts/spec.sh` runs a process
# per few spec files and hands their listings here; nothing else should need to.
#
# The report is the one `SpinelReport.report` prints for a single process,
# with `--blocked=N` capping the ranking of reasons (default 20, 0 for all).
# `--table` prints `bench/spec-status.md` instead. Either way it exits 1 when
# an example failed or a tag cannot be used, as one process does.
#
# awk, not Ruby on Spinel: a corpus run is tens of thousands of records, and
# Spinel is not yet fast enough to merge them quickly. Nothing here is more
# than counting.

set -euo pipefail
export LC_ALL=C

mode=report
blocked=20
listings=()
for argument in "$@"; do
  case "$argument" in
    --table) mode=table ;;
    --blocked=*) blocked="${argument#--blocked=}" ;;
    *) listings+=("$argument") ;;
  esac
done

records="$(mktemp)"
trap 'rm -f "$records"' EXIT
cat ${listings[@]+"${listings[@]}"} | grep -a '^LIST' | cut -f 2- > "$records" || true

# A section of `file: detail` lines, under a heading with their count.
section() {
  local heading="$1" kind="$2" lines
  # Once each: every process reports a fixture they all load, such as `pp`.
  lines="$(awk -F'\t' -v kind="$kind" '$1 == kind && !seen[$2 FS $4]++ { print "  " $2 ": " $4 }' "$records")"
  [[ -z "$lines" ]] && return
  printf '\n%s (%d):\n%s\n' "$heading" "$(printf '%s\n' "$lines" | wc -l | tr -d ' ')" "$lines"
}

if [[ "$mode" == table ]]; then
  echo "# ruby/spec status"
  echo
  echo "Regenerated by \`scripts/spec-status.sh\`. Never edited by hand — CI runs the script and fails if this file moved."
  echo
  # The platform is part of the measurement: ruby/spec's `platform_is` guards
  # run a different set of examples on each one.
  echo "Guards are answered for the platform the run is on. CI generates this file on Linux, so regenerate it there."
  echo
  echo "| directory | files | examples | passed | failed | blocked | skipped | passed % |"
  echo "|---|---:|---:|---:|---:|---:|---:|---:|"
  # A file counts toward its directory under `spec/ruby`, two levels at most:
  # `core/array`, `language`, `language/predefined`.
  awk -F'\t' '
    function row(files, passed, failed, blocked, skipped,   examples) {
      # `+ 0`: a count never incremented is the empty string, not 0.
      files += 0; passed += 0; failed += 0; blocked += 0; skipped += 0
      examples = passed + failed + blocked + skipped
      return files " | " examples " | " passed " | " failed " | " blocked " | " skipped " | " \
        (examples ? sprintf("%.0f%%", 100 * passed / examples) : "—")
    }
    $1 ~ /^(file|passed|failed|blocked|skipped)$/ {
      path = $2
      sub(/^spec\/ruby\//, "", path)
      n = split(path, parts, "/")
      directory = n == 1 ? "." : (n == 2 ? parts[1] : parts[1] "/" parts[2])
      count[directory, $1]++
      total[$1]++
      seen[directory] = 1
    }
    END {
      for (directory in seen) {
        print directory "\t" row(count[directory, "file"], count[directory, "passed"], \
          count[directory, "failed"], count[directory, "blocked"], count[directory, "skipped"])
      }
      print "~total\t" row(total["file"], total["passed"], total["failed"], total["blocked"], total["skipped"])
    }
  ' "$records" | sort -t "$(printf '\t')" -k 1,1 | awk -F'\t' '
    $1 == "~total" { print "| **total** | " $2 " |"; next }
    { print "| `" $1 "` | " $2 " |" }
  '
else
  failures="$(awk -F'\t' '$1 == "failed" { print "  " $2 " " $3 ": " $4 }' "$records")"
  if [[ -n "$failures" ]]; then
    printf 'failed (%d):\n%s\n\n' "$(printf '%s\n' "$failures" | wc -l | tr -d ' ')" "$failures"
  fi
  awk -F'\t' '
    { count[$1]++ }
    END {
      printf "%d files · %d examples · %d passed · %d failed · %d blocked · %d skipped\n", \
        count["file"], count["passed"] + count["failed"] + count["blocked"] + count["skipped"], \
        count["passed"], count["failed"], count["blocked"], count["skipped"]
    }
  ' "$records"
  section "fixtures that stopped part way" fixture
  section "stopped while loading" unloaded
  section "tag problems, see spec/tags/README.md" tag
  # Ranked by how many examples each reason accounts for, because that is the
  # order the remaining slices are worth doing in.
  ranked="$(awk -F'\t' '$1 == "blocked" { count[$4]++ } END { for (r in count) print count[r] "\t" r }' "$records" \
    | sort -t "$(printf '\t')" -k 1,1nr -k 2,2)"
  if [[ -n "$ranked" ]]; then
    reasons="$(printf '%s\n' "$ranked" | wc -l | tr -d ' ')"
    echo
    echo "blocked by, most examples first (https://github.com/ar4mirez/spinel/milestones):"
    shown="$reasons"
    [[ "$blocked" -ne 0 && "$blocked" -lt "$reasons" ]] && shown="$blocked"
    printf '%s\n' "$ranked" | head -n "$shown" | awk -F'\t' '{ printf "%7d  %s\n", $1, $2 }'
    if [[ "$shown" -lt "$reasons" ]]; then echo "  ... and $((reasons - shown)) more reasons"; fi
  fi
fi

if awk -F'\t' '$1 == "failed" || $1 == "tag" { found = 1 } END { exit !found }' "$records"; then
  # The table goes to a file; what kept it from being written goes to the
  # terminal.
  if [[ "$mode" == table ]]; then
    awk -F'\t' '
      $1 == "failed" { print "failed: " $2 " " $3 ": " $4 }
      $1 == "tag" { print "tag problem: " $2 ": " $4 }
    ' "$records" >&2
  fi
  exit 1
fi
